version: '3.8'
services:
    postgres:
        container_name: postgres_db
        build: init/.
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=terminal_postgres_db
        ports:
            - "5432:5432"
    cronjob:
        build: cronjob
        depends_on:
            - postgres
    airflow:
        image: apache/airflow
        command: scheduler
        restart: on-failure
        entrypoint: ./scripts/entrypoint.sh
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"