version: '3.8'
services:
    postgres2:
        container_name: terminal_postgres_db
        build: init/.
        environment:
            - POSTGRES_PASSWORD=root
        ports:
            - "5432:5432"
    postgres1:
        container_name: airflow_postgres_db
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    airflow:
        image: apache/airflow
        command: scheduler
        restart: on-failure
        entrypoint: ./scripts/entrypoint.sh
        depends_on:
            - postgres1
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"