version: '3.8'
services:
    java-notebook:
        build:
            context: ./java-notebook
        ports:
            - "8888:8888"
    postgres:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=root
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./Data_folder/terminal.csv:/Data_folder/terminal.csv
    cronjob:
        build: cronjob
        depends_on:
            - postgres
    airflow:
        image: apache/airflow
        command: scheduler
        restart: on-failure
        entrypoint: ./scripts/entrypoint.sh
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
        ports:
            - "8080:8080"